### ISSUE TITLE
Nothing besides the links in the article can be tabbed

### ISSUE THREAD

**Issue by avaseghi** [wenqili/adjacent#11]
Everything (i.e. text), with the exception of links, past the headers in the articles are not able to be tabbed.

**Comment by keerthanapareddy** [comment]
Tabbing through texts ensures voice over

**Comment by wenqili** [comment]
I checked the voiceover. Voiceover works perfect on article page. All the text are readable.

Is there any reason or standards that request text to be tabbed?
They shouldn't be tab-able content.

**Comment by avaseghi** [comment]
Sorry Wenqi. That was our mistake. According to Jenny, “If its just plain text, then no, it does not need to be tabbable. However, any sort of interactive text (links, form elements, etc) should be reachable through tabbing.”
