### ISSUE TITLE
issue 5 :: Remove unnecessary capitalizations in article titles on home page

### ISSUE THREAD

**Issue by avaseghi** [wenqili/adjacent#16]
Voiceover reads series of capitalized headers as individual letters. For example, in "Want an intelligent machine? Give it a body" is read as "Give I-T a body".

**Comment by wenqili** [comment]
This is not a A11y issue.
Voiceover recognizes IT as abbreviation for Information Technology.
Voiceover works fine on the other capitalized titles.

**Comment by avaseghi** [comment]
Hey Wenqi, this issue is also occurring with voiceover and some of the names in the about page. It is literally reading the spelling of the names. Is there someway we can correct that?

**Comment by wenqili** [comment]
We will discuss the solution tomorrow in the weekly meeting.
It's an easy fix if we just use regular text. If we have to keep to Capitalized design, I'll add ARIA description to them manually.
